"""Generate AstrBot requirements from direct PEP 621 dependency declarations."""

import argparse
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = (
    "# Generated by: uv run --locked python scripts/requirements.py\n"
    "# Direct dependencies from pyproject.toml; do not edit by hand.\n"
    "# uv.lock pins development only, not AstrBot's shared environment.\n"
)


def render(project_file: Path) -> str:
    with project_file.open("rb") as source:
        project = tomllib.load(source)["project"]
    if "dependencies" in project.get("dynamic", []):
        raise ValueError("Dynamic dependencies are not supported; declare project.dependencies.")
    dependencies = project.get("dependencies", [])
    if not isinstance(dependencies, list) or any(
        not isinstance(item, str)
        or not item.strip()
        or "\n" in item
        or "\r" in item
        or item.lstrip().startswith(("-", "#"))
        for item in dependencies
    ):
        raise ValueError("project.dependencies must contain single-line requirement strings.")
    return HEADER + "".join(f"{item}\n" for item in dependencies)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or verify AstrBot direct requirements.")
    parser.add_argument(
        "--check", action="store_true", help="Fail if requirements.txt is stale; do not write."
    )
    args = parser.parse_args()
    try:
        expected = render(ROOT / "pyproject.toml")
    except (OSError, ValueError, KeyError) as exc:
        parser.exit(1, f"Cannot generate requirements: {exc}\n")
    target = ROOT / "requirements.txt"
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            parser.exit(
                1,
                "requirements.txt is stale. Run: uv run --locked python scripts/requirements.py\n",
            )
        print("requirements.txt matches pyproject.toml direct dependencies.")
    else:
        target.write_text(expected, encoding="utf-8")
        print("Generated direct requirements.txt from pyproject.toml.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
