"""Generate or check AstrBot requirements using the committed uv lockfile."""

import argparse
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPORT_ARGS = [
    "uv",
    "export",
    "--locked",
    "--no-dev",
    "--no-editable",
    "--no-emit-project",
    "--no-hashes",
    "--no-header",
    "--format",
    "requirements-txt",
]
HEADER = (
    "# Generated by: uv run --locked python scripts/requirements.py\n"
    "# Do not edit; update pyproject.toml and uv.lock instead.\n"
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Export or verify AstrBot runtime requirements.")
    parser.add_argument(
        "--check", action="store_true", help="Fail if requirements.txt is stale; do not write."
    )
    args = parser.parse_args()
    # --locked fails on stale pyproject/lock pairs instead of resolving silently.
    result = subprocess.run(EXPORT_ARGS, cwd=ROOT, capture_output=True, text=True)
    if result.returncode:
        parser.exit(result.returncode, result.stderr)
    expected = HEADER + result.stdout
    target = ROOT / "requirements.txt"
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            parser.exit(
                1,
                "requirements.txt is stale. Run: uv run --locked python scripts/requirements.py\n",
            )
        print("requirements.txt matches uv.lock.")
    else:
        target.write_text(expected, encoding="utf-8")
        print("Exported requirements.txt from uv.lock.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
